name: .NET Framework Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Mono
      run: sudo apt-get install -y mono-complete

    - name: Build with MSBuild
      run: |
        msbuild NetSatis.Entities/NetSatis.Entities.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2
        msbuild NetSatis.FrontOffice/NetSatis.FrontOffice.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.6
        msbuild NetSatis.BackOffice/NetSatis.BackOffice.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2
