name: .NET Framework Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MSBuild
      run: |
        sudo apt-get update
        sudo apt-get install -y msbuild

    - name: Install .NET Framework 4.7.2
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/aa2cd114-4853-4b43-8c8f-9b5f04ef79c0/0d2568d2ebf0a857ef49c4cc2b73d214/ndp472-devpack-enu.exe
        wine ndp472-devpack-enu.exe /q

    - name: Install .NET Framework 4.6
      run: |
        wget https://download.microsoft.com/download/0/8/C/08C19FA4-4F8C-4E6A-9C5E-9787E1AB8B3C/NDP46-KB3045557-x86-x64-AllOS-ENU.exe
        wine NDP46-KB3045557-x86-x64-AllOS-ENU.exe /q

    - name: Build with MSBuild
      run: |
        msbuild NetSatis.Entities/NetSatis.Entities.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2
        msbuild NetSatis.FrontOffice/NetSatis.FrontOffice.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.6
        msbuild NetSatis.BackOffice/NetSatis.BackOffice.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2
