name: .NET Framework Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: 'latest'

    - name: Setup .NET Framework 4.7.2
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: 'latest'
        include-prerelease: true
        target-framework: '4.7.2'

    - name: Setup .NET Framework 4.6
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: 'latest'
        include-prerelease: true
        target-framework: '4.6'

    - name: Build with MSBuild.exe
      run: |
        msbuild.exe NetSatis.Entities\NetSatis.Entities.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2
        msbuild.exe NetSatis.FrontOffice\NetSatis.FrontOffice.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.6
        msbuild.exe NetSatis.BackOffice\NetSatis.BackOffice.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2
